[programs.localnet]
messengerapp = "DVNmvoqvDwM11XZBC5qUSWdFtegwEEirb1jtmqhTrssq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yaami_dancho/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
